//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comic.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was built and developed by Tiktak and ComicToGo team..
        /// </summary>
        public static string AboutUs_Content1 {
            get {
                return ResourceManager.GetString("AboutUs_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For additional information, please click on the following link.
        /// </summary>
        public static string AboutUs_Content2 {
            get {
                return ResourceManager.GetString("AboutUs_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about us.
        /// </summary>
        public static string AppBar_AboutUs {
            get {
                return ResourceManager.GetString("AppBar_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string AppBar_Categories {
            get {
                return ResourceManager.GetString("AppBar_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete all.
        /// </summary>
        public static string AppBar_DeleteAll {
            get {
                return ResourceManager.GetString("AppBar_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chapters list.
        /// </summary>
        public static string AppBar_Menu {
            get {
                return ResourceManager.GetString("AppBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string AppBar_Next {
            get {
                return ResourceManager.GetString("AppBar_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string AppBar_Previous {
            get {
                return ResourceManager.GetString("AppBar_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate it!.
        /// </summary>
        public static string AppBar_Rate {
            get {
                return ResourceManager.GetString("AppBar_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBar_Refresh {
            get {
                return ResourceManager.GetString("AppBar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBar_Search {
            get {
                return ResourceManager.GetString("AppBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format.
        /// </summary>
        public static string AppBar_TextEdit {
            get {
                return ResourceManager.GetString("AppBar_TextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top popular.
        /// </summary>
        public static string AppBar_Top {
            get {
                return ResourceManager.GetString("AppBar_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories.
        /// </summary>
        public static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chapters.
        /// </summary>
        public static string ChapterList {
            get {
                return ResourceManager.GetString("ChapterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter key word.
        /// </summary>
        public static string EnterKeyWord {
            get {
                return ResourceManager.GetString("EnterKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t communicate with server to retrieve data. You want to close App?.
        /// </summary>
        public static string Error_Connection {
            get {
                return ResourceManager.GetString("Error_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occur.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my novels.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;&lt;/body&gt;
        ///&lt;html&gt;.
        /// </summary>
        public static string HtmlFooter {
            get {
                return ResourceManager.GetString("HtmlFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;link href=&apos;http://fonts.googleapis.com/css?family=Noto+Serif&apos; rel=&apos;stylesheet&apos; type=&apos;text/css&apos;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no&quot; /&gt;
        ///	&lt;style&gt;
        ///	body{
        ///		font-size:13pt;
        ///		width:100%;
        ///		color: #582700;
        ///		background: #FFEFD4;
        ///		}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///function ChangeFontFamily(){
        ///	
        ///}
        ///&lt;/script&gt;
        ///&lt;body id=&quot;pageBody&quot;&gt;.
        /// </summary>
        public static string HtmlHeader {
            get {
                return ResourceManager.GetString("HtmlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last updated.
        /// </summary>
        public static string LatestTitle {
            get {
                return ResourceManager.GetString("LatestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Content.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a match.
        /// </summary>
        public static string SearchEmpty {
            get {
                return ResourceManager.GetString("SearchEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your keyword.
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH RESULTS.
        /// </summary>
        public static string SearchResultLabel {
            get {
                return ResourceManager.GetString("SearchResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP POPULAR.
        /// </summary>
        public static string TopPopular {
            get {
                return ResourceManager.GetString("TopPopular", resourceCulture);
            }
        }
    }
}
